### ISSUE TITLE
Using wp_localize_script in Child Theme

### ISSUE THREAD

**Issue by edmacfly** [understrap/understrap#598] opened 2018-03-15 20:07 UTC
I've successfully added some custom JS using the gulp file, however, I have one script that I need to pass some variables to from PHP. I would normally use the wp_localize_script within functions.php, but as this is not the preferred way to enqueue scripts within Understrap I wondered if there is another way to achieve this. I appreciate any help anyone can offer.

**Comment by Thomas-A-Reinert** [comment] 2018-03-17 22:51
Hm. This is a - very interesting though! - edge-case, I guess. And as far as I know this doesn´t get handled by UnderStrap in any way (yet).

Would you be able to clarify what you intend to achieve please? I´m really willing to help but I need a use-case (and maybe already existing code) to reproduce, okay?

**Comment by edmacfly** [comment] 2018-03-18 15:51
Hi Thomas, thanks for replying to my question. I'm building a site for a sculptor using understrap and understrap-child. I'm using a jquery plugin called three-sixty slider (https://github.com/creativeaura/threesixty-slider) to create a series of gallery pages with three sixty views of her work. In order to launch the plugin, you need to tell it the name of the div that has to have the 360 image in, along with the location of the photos that make up the 360 along with a series of other variables. I was hoping to combine use the advanced custom fields plugin and combine that with the localize code to be able to pass the variables to the plugin. Am I going about this the right way? Thanks again.

**Comment by Thomas-A-Reinert** [comment] 2018-03-20 00:21
Hi Ed,

it seems that this plugin is no longer maintained - but that´s just a sidenote. I know of none better..

To make sure that I can follow your exact way on how you plan to integrate it, I´d probably need a dump of your dev-site (probably best done with the [Duplicator Plugin](https://wordpress.org/plugins/duplicator/))

So long i´ll just have to guess to find a solution/workaround.
* I guess your 360° stuff will just appear on a certain template/post-type.
* Post-types/templates can be queried and/or will be auto-applied
* I guess you´ll want to initiate the script just before the closing &lt;/body> - so insert a script there and access the variables (defined through AFC) from there and populate them to the custom JS.

At least that would be my approach which I followed with different customer requests built pon UnderStrap. But I´m sorry to tell you - that´s probably beyond UnderStraps´ "general" Scope.  As I said - it´s an edge-case, something probably most of UnderStraps users/developers will never ever need - or will have to find a custom solution for.

However, I´m still with it and trying to help. If there´s any way to smarten up my approach, i´d be totally with it ;)

**Comment by edmacfly** [comment] 2018-03-20 09:45
Hi Thomas, thank you so much for getting actively involved with my challenge. I will finish off the development site in order to get the 360 functionality working and will then send you a copy for investigation. I think you are right in that this is a bit of edge-case issue, I guess it would maybe be an appropriate situation for turning the jQuery plugin into a Wordpress plugin? Either way, I'll post back soon. Cheers, Ed.

**Comment by Thomas-A-Reinert** [comment] 2018-04-16 23:34
Hey @edmacfly , due to the fact

- that  no follow up has been posted
- it seems to be an edge-case

.. I´ll close that topic for housekeeping

**Closed by Thomas-A-Reinert** 2018-04-16 23:34 UTC
Labels: Feature request, Question
