### ISSUE TITLE
Gulp watch-bs: Saving WP post with image, increments ":3000" onto img src's

### ISSUE THREAD

**Issue by digitaloutback** [understrap/understrap#704] opened 2018-06-06 13:25 UTC
I have inserted an image from the media library. It inserts the image without ":3000" but immediately it is added. Saving the post adds another :3000 ending up with image paths like ".../something.jpg:3000:3000:3000:3000"

**Comment by Thomas-A-Reinert** [comment] 2018-06-11 23:55
Hm, does the problem still persist?
If so: please fill out the issue-template, so we can (try) to reproduce the problem, okay?

Closing it, because essential information didn´t get supplied.

**Closed by Thomas-A-Reinert** 2018-06-11 23:55 UTC
