### ISSUE TITLE
Image caption text displayed outside the figcaption tag and add an extra div

### ISSUE THREAD

**Issue by evandropastor** [understrap/understrap#335] opened 2017-06-01 00:50 UTC
Hello,

I found a problem with the figcaption: when I add a caption on the image this caption text is displayed outside the figcaption tag, like so:

`...<figcaption></figcaption></figure></div> ""Caption text
`

**Comment by axlright** [comment] 2018-03-20 04:14
Closing this issue because it hasn't been commented on in over a year. Also, I cannot reproduce the issue. When adding a test caption to an image in a post, I get:
`<figcaption class="wp-caption-text">Here’s a caption I’d like to list for this image. How does it appear on the front end?</figcaption></figure>`

 Please comment if this issue persists and I can re-open the issue.

**Closed by axlright** 2018-03-20 04:14 UTC
