### ISSUE TITLE
Excess div on page.php, single.php v0.81

### ISSUE THREAD

**Issue by jack-fdrv** [understrap/understrap#622] opened 2018-03-28 20:23 UTC
Hello, here is the default page template where we see extra closed div tag for primary.
https://src.fdrv.guru/180328231859.jpg

Or I miss something?

**Comment by Thomas-A-Reinert** [comment] 2018-03-28 20:50
I guess this is a dupe of #513 , right? You can find the answer there. I´m totally with you that this is not very elegant and should be solved differently. But *hey* that´s currently not on top of the priority-list ;)

**Comment by ZacharyElkins** [comment] 2018-03-29 17:26
The opening ‘#primary’ div is generated by the **global-templates/left-sidebar-check.php** template. It is the ‘col-x-x’ class which is necessary to remove the negative margin of ‘row’. 

To me, the wrapper seems unnecessary, as you can target pages and sections by classes in the body tag. It does provide top and bottom margins, but that could be put on something else. The primary, although bulky, helps produce correct sidebar layout, when there is a sidebar. 

With no sidebar you could remove ‘row’ and ‘#primary’ and just let your content be in the container, then when you use ‘row’ and ‘col’ classes to format other parts they wouldn’t be nested in an extra ‘row’ and ‘col’. 

The ‘main’ tag is for HTML5. The ‘container’ div could be replaced by main, right? Or would that not be ideal? I’m not sure what the rules are with main beyond there only being one, and it not being under certain HTML5 tags. The wrapper could also be replaced by main.

**Comment by holger1411** [comment] 2018-03-29 18:12
@jack-fdrv Hm, maybe you are right. I received several mails every month asking for the missing <div> (which is inside the left-sidebar-check.php).
So we have a balanced number of opening and closing tags within this file ;-)

**Comment by holger1411** [comment] 2018-03-29 18:14
Argh, don´t want to be sarcastic...just seeing now that you inital issue was about a missing div...

**Comment by holger1411** [comment] 2018-04-12 18:36
Done here: https://github.com/understrap/understrap/commit/548f4f04c1947da6e5238d8a17309e50e8bf8789
 Thx @jack-fdrv !
Will check and test it a bit and will be shipped with 0.8.3

**Comment by jack-fdrv** [comment] 2018-04-14 01:45
Well, I am so happy that my idea was helpful and you are implement it! =)

**Comment by holger1411** [comment] 2018-04-15 17:03
Closing this issue becasue it was fixed and shipped with 0.8.2. Thx @jack-fdrv !

**Closed by holger1411** 2018-04-15 17:03 UTC
Labels: Enhancement, Needs investigation
