### ISSUE TITLE
Content width after upgrade

### ISSUE THREAD

**Issue by fredroo** [understrap/understrap#840] opened 2018-11-02 03:26 UTC
Please delete anything that does not apply for you!

## Issue is about..
  - [ X ] a Bug Report
  - [ ] a Feature Request
  - [ ] a Suggestion
  - [ ] a Question
  - [ ] I need help

## Please tell us about your environment:

  - **WordPress Version:** 4.9.8
  - **OS Version:** [Windows 7 | Windows 8 | Windows 10] | Linux [Distribution / Version] | MacOS [Version] | Android [Version] | iOS [Version]
  - **Browser:** [ all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
  - **Language:** [ all | PHP | SQL | HTML | S/CSS | Javascript | jQuery | ES6 | JSON | XML]
  - **Node.js & NPM Versions:** Node.js [V X.XX] | NPM [V X.XX]

---

# Issue Overview for Bugreports

post width changed to full after upgrade

## Steps to reproduce?
Only upgrade to the last version

My website is:
https://thefonts.download/
Error show and all posts:
https://thefonts.download/fonts/102/hirosh/

## Expected behavior

# Todos

 * Test
 * Documentation

**Comment by Thomas-A-Reinert** [comment] 2018-11-03 02:18
- I am missing an understandable bug report.
- None of the questions in the bug report template has been answered.
- Steps to reproduce just says "Only upgrade to the last version". From which version?

Closing the issue due to non-reproducability and not complying to the issue request template that would have given more reproducable information.

**Closed by Thomas-A-Reinert** 2018-11-03 02:18 UTC

**Comment by fredroo** [comment] 2018-11-08 02:41
@Thomas-A-Reinert after upgrading my right sidebar 

is appearing the sidebar after content because of this

understrap/global-templates/left-sidebar-check.php line 21 

CSS class "col-md"

I fixed after changed to "col-md-8"

but the left sidebar does not show when I changed to the left sidebar

example fixed: https://thefonts.download/fonts/107/independence/

my website works fine now https://thefonts.download

**Comment by fredroo** [comment] 2019-04-15 11:15
@Thomas-A-Reinert 
please change line 19
from
<div class="col-md content-area" id="primary">
to
<div class="col-md-8 content-area" id="primary">
