### ISSUE TITLE
How to remove sidebar only on cart and checkout pages?

### ISSUE THREAD

**Issue by marlenariddell** [understrap/understrap#528] opened 2018-01-19 15:27 UTC
I have a woocommerce site where I need to show the sidebar on most pages, however I'd like to hide it on the cart and checkout pages. Can anyone tell me which template file to edit? Or should I be adding something to functions for this?  Thanks!

**Comment by typeplus** [comment] 2018-01-21 05:40
You can edit the actual pages and specify full width or another template or you can write some PHP to hide the components on these pages targeting them `if ( is_cart() || is_checkout() )` in your functions.php. Let me know if you want more info.

**Comment by marlenariddell** [comment] 2018-01-22 15:45
Hey,

I have the line for checking if it's a cart or checkout page, but I'm not sure how to target the sidebar and hide it. Would love an example if possible. 

Thanks!

**Comment by uitta** [comment] 2018-01-25 15:48
if you like to use the code,first of all you have to understand what file is beeing used and then use the code with an if statement to hide the sidebar.
Else you can choose the cart/checkout page in admin and select a layout without the sidebar (see attachment).

![schermata 2018-01-25 alle 16 48 10](https://user-images.githubusercontent.com/25509550/35397375-9dda0df4-01ef-11e8-9bb4-a79e30275008.png)

**Comment by typeplus** [comment] 2018-01-26 02:19
@uitta I suggested that in the first post and it is by far the easiest solution 😀

**Comment by Thomas-A-Reinert** [comment] 2018-03-02 18:08
Seems the issue is solved, so i´ll close it.

**Closed by Thomas-A-Reinert** 2018-03-02 18:08 UTC
