### ISSUE TITLE
Issue with pagination in 0.8.2

### ISSUE THREAD

**Issue by mercray** [understrap/understrap#651] opened 2018-04-19 23:19 UTC
## Issue is about..
  - [ ] a Bug Report

## Please tell us about your environment:

  - WordPress Version: 4.9.5
  - OS Version: Windows Server 2012 R2
  - Browser: All
---
![404 example](https://user-images.githubusercontent.com/38543961/39023019-a1819ab6-447b-11e8-81ed-04853e03f9f5.png)

# Issue Overview for Bugreports

Pagination seems to have changed between 0.8.1 and 0.8.2. After upgrading, the last page is now displaying a "next" page button that when pressed takes you to a 404 page. There is no "next" page button displayed with 0.8.1.

## Steps to reproduce?

Install 0.8.2 theme and navigate to the last page in either category or main index page and press next button.

### Other Comments
 Downgrading to 0.8.1 resolves the issue.

**Comment by Thomas-A-Reinert** [comment] 2018-04-19 23:26
Hrmpf. Thanks for submitting this probable bug.
Cannot currently reproduce, because i´m stuck in a project. Will assign others who may be able to reproduce, okay? Just wanted to give you a quick-response.

Questions: This happens just within the parent-theme or also within the child? Or is this ONLY Child-theme related?

**Comment by mercray** [comment] 2018-04-19 23:38
I have a child theme I have written that was working fully with 0.8.1 – I’m fairly new to WP theme writing so fully expected it was something I had done. Therefore I activated the Understrap (parent) theme itself and the issue still existed, so I thought I should report it.

**Comment by Thomas-A-Reinert** [comment] 2018-04-19 23:53
Hey @mercray please don´t feel discredited - but you´re in the wrong section. But Child-theme related topics should be handled in the [CHILD-THEME-REPOSITORY](https://github.com/understrap/understrap-child).

That doesn´t mean that we´re not willing to help you ASAP we find the time - but everything should match its topic. And we´re in UnderStrap PARENT Theme right now. This was exactly why I was asking.

Closing it because of non-affliation (?!) to this repository.

REALLY - please get back to us on the child-theme repo. We really want to get it fixed if it´s a common and reproducable problem. It just makes no sense to resolve it here.

**Closed by Thomas-A-Reinert** 2018-04-19 23:53 UTC
