### ISSUE TITLE
custom-editor-style.scss not generating .min.css or .min.map files

### ISSUE THREAD

**Issue by bluehiveinteractive** [understrap/understrap#937] opened 2019-03-10 00:32 UTC
## Issue is about..
  - [x] a Question

## Please tell us about your environment:

  - **WordPress Version:** 5.1.0
  - **OS Version:** MacOS 
  - **Node.js & NPM Versions:** Node.js [V 10.15.3] | NPM [V 6.4.1]

---

# Issue Overview for Bugreports

All css files are not minified and no sourcemap created except for theme.css For example /sass/custom-editor-style.sass doesn't generate a /css/custom-editor-style.min.css or /css/custom-editor-style.min.map file when you edit custom-editor-style.scss.

Also if you create a new scss file such as /sass/my-test.scss the /css/my-test.css file is created, but it doesn't create a /css/my-test.min.css or /css/my-test.min.map

## Steps to reproduce?

Start with a fresh download of understrap. Delete the /css/custom-editor-style.min.css and the /css/custom-editor-style.min.map files, run `gulp watch` and then go open /sass/custom-editor-style.scss and make a change, the /css/.min and /css/.map files are not regenerated.

## Expected behavior
.min.css and .min.map files for all /css/*.css files should be created

### Other Comments

It could be possible that this isn't how the gulpfile.js is configured to run, but since a fresh copy of understrap is distributed with both /css/custom-editor-style.min.css and /css/custom-editor-style.min.map I assumed that when you edit /sass/custom-editor-style.scss that it would regenerate the appropriate min and map files.

**Comment by 0dp** [comment] 2019-03-14 12:59
It does not look like the gulp task takes any special care of custom-editor-style.scss/css Instead we can assume that it is being included in theme.(min).css

If you look here
![Screenshot 2019-03-14 at 13 58 39](https://user-images.githubusercontent.com/3642367/54358707-4b438900-4661-11e9-986f-e335f4cb4dd3.png)
You can actually see it is garbage :/

**Comment by Thomas-A-Reinert** [comment] 2019-03-22 20:36
Yeap, confirmed. And what @0dp said, is exactly what I do manually, because I don´t want my customers to really access any style but just a few selected for text-formatting.

Anyway, that will not add it to the editor and/or make it accessible from there. To make your selected styles appear in the editor you´ll need to edit `inc/editor.php` and add your styles to the existing array there.

Example:
```
array(
  'title'  => '.txt-white', // Text to show in the "Formats" Select-box
  'selector' => 'p,ul,li',  // Tags that style can be applied to
  'classes' => 'txt-white',  // Class you´ll want to address
  'wrapper' => false, // If it should have a wrapper around
),
```

**Comment by Thomas-A-Reinert** [comment] 2019-07-03 00:06
@0dp - Yes "your workaround works". But I guess you can confirm that it is not really "elegant".

I really don´t know if that´s possible, but it would be great if one would be able to add a flag like "`backend-editor = 1`" to ANY style that is in "`./sass/theme/_theme.scss`" (and further included files) and ONLY THOSE that would then get generated into a "`./css/custom-editor-style.css`" and also .min and .map Files.

Maybe that´s too much to ask for, but it WOULD BE GREAT :)

Anyway. Closing this topic due to no feedback of the original poster within more than a fortnight.

**Closed by Thomas-A-Reinert** 2019-07-03 00:06 UTC
Labels: Question
