### ISSUE TITLE
Navbar is not getting rendered on checkout

### ISSUE THREAD

**Issue by lajos93** [understrap/understrap#803] opened 2018-09-11 09:32 UTC
The latest commit when it was working is cc695d5
It's still rendered at this point:
![image](https://user-images.githubusercontent.com/9155141/45350829-02791d80-b5b5-11e8-9db9-7d956241bb20.png)

Currently it returns an empty container ON CHECKOUT
![image](https://user-images.githubusercontent.com/9155141/45350880-276d9080-b5b5-11e8-90b4-ed86aea67ce1.png)

**Comment by holger1411** [comment] 2018-10-15 12:56
Can´t reproduce it on the demo site:
https://understrap.com/understrap/?post_type=product
Can you check it there?

**Comment by Thomas-A-Reinert** [comment] 2018-12-30 03:20
Issue seems to be resolved / abandoned / or whatsoever. Closing it for house-keeping. Feel free to re-open if the problem persists.

**Closed by Thomas-A-Reinert** 2018-12-30 03:20 UTC
