### ISSUE TITLE
Please provide a short summary of the problem (approx. 50 characters)

### ISSUE THREAD

**Issue by gurds91** [understrap/understrap#1786] opened 2022-06-22 13:44 UTC
![understrap errors](https://user-images.githubusercontent.com/107938466/175044166-05e1cc26-694a-4a2d-8e9b-dff2cf1fbe88.JPG)

**Describe the problem**
Hi, I joined Instant Understrap course recently , downloaded node.js on my computer, according to the software it says I have Node.js v16.15.1.

I am using version 1.1.0 understrap child theme (called understrap-child). I want to develop with the child theme. When I went into Visual Studio code, opened the instant-understrap-child theme , went into terminal and typed in node -v to check version , it outputted red text errors. 

I also inputted npm install --global gulp-cli and it came back with red errors ;(

Please help, I have attached problem. Is there a dedicated email where I can ask for help for people who joined and paid for instant understrap course? On my computer I have Git GUI, Git bash and Git CMD , no idea what each of those are for.![understrap errors](https://user-images.githubusercontent.com/107938466/175044072-92ece207-91f0-4ad8-8de0-90f4a969a93b.JPG)
**Debug Checklist**
Please include all of the following:
- [ ] The version of Understrap you're using (located in the package.json file)
- [ ] Whether you are developing with Understrap or the Understrap child theme
- [ ] The output of `node -v`
- [ ] The output of `git --version`
- [ ] The output of `gulp -v` (if using an Understrap version below 1.0.0)

**Screenshots / Videos**
If applicable, add screenshots/videos to help explain your problem.

**Code**
If applicable, provide code to help explain your problem.

**Additional context**
Add any other context about the problem here (e.g. related issues).

**Comment by IanDelMar** [comment] 2022-06-23 02:46
Can you please check whether the path to node is set in your `PATH` environment variable and add it if it's missing?

Assuming node is installed in "C:\Program Files\nodejs\", follow these steps:
1. Run VS Code as administrator. 
2. Open the terminal.
3. Type `$env:Path -split ';'` in the terminal. 
4. Look for C:\Program Files\nodejs\.
5. If C:\Program Files\nodejs\ is missing in the path variable, type `[Environment]::SetEnvironmentVariable("PATH", $Env:PATH + ";C:\Program Files\nodejs\", [EnvironmentVariableTarget]::Machine)` to add it.
6. Restart VS Code.

**Comment by gurds91** [comment] 2022-06-23 09:50
I tried that, it's telling me version number now when I type command node -v.  If I need further help I will post in here my issues. Thx

**Comment by gurds91** [comment] 2022-06-23 10:07
Thanks

So as my version doesn't depend on GULP , do I just type in npm install
command after node.js installed , is this correct?

**Comment by IanDelMar** [comment] 2022-06-24 07:20
> Thanks So as my version doesn't depend on GULP , do I just type in npm install command after node.js installed , is this correct?

Yes, that's correct. You have to type `npm install` to install all the necessary dependencies.

**Comment by IanDelMar** [comment] 2022-06-24 07:29
Please consider
* closing this issue as it is resolved.
* editing the "title" of the issue to give information what the issue is about (currently it's just "Please provide a short summary of the problem (approx. 50 characters)")
* opening a different issue for a different problem.

**Comment by bacoords** [comment] 2022-09-26 22:57
Closing this issue due to lack of response, but please comment if it needs to be re-opened.

**Closed by bacoords** 2022-09-26 22:57 UTC
Labels: Help wanted!
