### ISSUE TITLE
Css & Js browser caching

### ISSUE THREAD

**Issue by gintsmurans** [understrap/understrap#631] opened 2018-04-05 14:11 UTC
## Issue is about..
  - [x ] a Feature Request

Hi! How about a proposal to add some kind of minified css and js file versioning. While developing a new theme I am getting tired of browser not always loading latest version, so as a quick fix I have modiefied enqueue.php like this:

    <?php
    /**
     * Understrap enqueue scripts
     *
     * @package understrap
     */
    
    if ( ! function_exists( 'understrap_scripts' ) ) {
    	/**
    	 * Load theme's JavaScript sources.
    	 */
    	function understrap_scripts() {
    		// Get the theme data.
    		$the_theme = wp_get_theme();
    		$theme_version = $the_theme->get( 'Version' );
    		
    		$css_version = $theme_version . '.' . filemtime(get_template_directory() . '/css/theme.min.css');
    		wp_enqueue_style( 'understrap-styles', get_stylesheet_directory_uri() . '/css/theme.min.css', array(), $css_version );

    		wp_enqueue_script( 'jquery');
    		wp_enqueue_script( 'popper-scripts', get_template_directory_uri() . '/js/popper.min.js', array(), $theme_version, true);
    		
    		$js_version = $theme_version . '.' . filemtime(get_template_directory() . '/js/theme.min.js');
    		wp_enqueue_script( 'understrap-scripts', get_template_directory_uri() . '/js/theme.min.js', array(), $js_version, true );

    		if ( is_singular() && comments_open() && get_option( 'thread_comments' ) ) {
    			wp_enqueue_script( 'comment-reply' );
    		}
    	}
    } // endif function_exists( 'understrap_scripts' ).
    
    add_action( 'wp_enqueue_scripts', 'understrap_scripts' );

**Comment by holger1411** [comment] 2018-04-06 17:42
@gintsmurans Thx! Will try and test it.
There are several issues about this

**Comment by holger1411** [comment] 2018-04-07 13:29
Add it here:
https://github.com/understrap/understrap/commit/4fb9fdd96dc34dc3d64356236b495e7da3de2a78
and it is live on our demo site:
https://understrap.com/understrap
If there are no problems/issues with your solution we will ship it with 0.8.2

Thx @gintsmurans

**Comment by axlright** [comment] 2018-04-09 02:42
Thanks @gintsmurans and @holger1411 for giving it a go. I never seem to have lag with browsers not picking up current stylesheets and js files during development, but this looks cool. Why wouldn't you leave it in place after launching the production site? The idea that your css and js files are only updated when your theme updates (using the theme version number for the query string) is pretty ridiculous. So why not leave these more granular query strings?

**Comment by 0dp** [comment] 2018-04-09 06:05
Isn't there something about page insight gives you negative rating for query strings?

**Comment by gintsmurans** [comment] 2018-04-09 07:13
@holger1411 Nice. :)

@axlright I would also leave it in production. There usually are issues with other people not seeing changes after updating css / js files. To avoid this - Changes are live. I don't see them. - confusion I am always using some kind of css, js versioning.

**Comment by holger1411** [comment] 2018-04-13 19:15
@axlright: I have to explain why people can´t see the new changes and why they have to clear there browser cache first, several times a week. ;-) 
Will save a lot of my lifetime!

Especially if you ship updates several times a day you must make sure that your coworkers and the visitors will see the latest version without doing something. And I don´t want to increase the themes version number just because I change one line of scss...

So a files timestap is a relatively clear indicator for: "Here is something new in this file."
A version number itself istn a clear indicator for changes in a specific file. It is more an indicator for "Here is something new in this package of files"

**Comment by axlright** [comment] 2018-04-13 19:53
@holger1411 I'm totally behind the concept. 

I just somehow don't have clients or my dev team having trouble seeing new content. Maybe it's our host? All my client sites are hosted on WP Engine. Some use Cloudflare for CNAME flattening and DNS caching, and for those I need to clear the DNS cache. But for sites that aren't on Cloudflare, when I push css, js or php changes, I almost never hear the whole "I can't see that" from clients. 

I often do client reviews where I'm doing git push directly to the server while on the phone / Slack with the client and they just refresh and see everything new.

Who knows. Either way, it's all good - I support the decision :-)

**Comment by Thomas-A-Reinert** [comment] 2018-04-13 22:57
If I may weigh in my 2cent..

To mention something positive first: Going for a timestamp is MUCH better than going for the version number which won´t change too often!

@0dp  - you´re absolutely correct. It HAS an impact on GTMetrix / Pingdom / PS Insights / WebPageTest and the likes. So in my eyes it´s contraproductive to work against a clients "stupidity" (sorry, no offense intended) by implementing a feature that works against your own performance score. Performance is everything these days and can be resolved easily whereas clients stupidity probably won´t get resolved within the next 10k years ;)

The time that you need to teach a client to "force reload" is in my eyes less than trying to explain why their ranking doesn´t get the full score and which impact it may have.

Yes, there are workarounds. 
1. To avoid punishment by scoring tools: https://wordpress.org/plugins/remove-query-strings-from-static-resources/ - Another needless plugin imho that may also cause lag and other performance issues, another one you/your client needs to update etc. pp.
2. For your clients: Just tell them to click "Clear Session" after every new iteration - https://chrome.google.com/webstore/detail/clear-session/maejjihldgmkjlfmgpgoebepjchengka . @holger co-workers ain´t a reason in my eyes. If they´re too silly to make forced reload suggest ´em to get a new job! Sorry, that may sound harsh but welcome to the web-industry!

It doesn´t affect development anyways when you use `gulp watch-bs` .

So I would _strictly_ vote against leaving that in production!

To suggest something more fruitful - but maybe not too easy to implement: Why don´t we rewrite the css base-filename on datechange? Yes of course, that would need to adjust the implementation of it in functions.php .. But that would solve all problem in one - cachebusting as well as performance-degradation.

Sidenote: Seems that it didn´t get implied in the child theme yet, right?

**Comment by holger1411** [comment] 2018-04-14 03:50
@Thomas-A-Reinert Thx for weighting in.

Basically, of course, you are right: If something impacts the performance there must be a very very very good reason for it. And it isnt a good reason if it just improves the workflow of a dev, while thousands of websites will render slower than before.

But is there an impact on performance?

Just to understand it (I am not too much into how Browsers work...):
The time stamp behind the filename changed just if the file was changed. Than it is necessary that the browser loads the file again. 
There are a lot of reason why visitors should see changes on your website if they revisited it, far beyond just pleasing imaptient clients. For example if you fix a JS bug. You don´t want to let your users browser decide when they see the fix. You want that revisiting users don´t get the bug anymore, instantly.

And if there are no changes the browser don´t have to reload the file again. So in this case there is no performance imapcet (or?)

So for me the most important question here is: Is there a performance impact of @gintsmurans solution even if there are no changes to the JS or CSS file?

**Comment by ZacharyElkins** [comment] 2018-04-14 17:55
I’m not sure about the performance impact, but I’m sure that PageSpeed has their reasons.

I typically use some sort of caching plugin, which bundles all my CSS and sometimes JS files (selectively on the JS). This seems to get rid of any lag as the caching plugin loads it’s own file after processing and usually has a random file name.

I’ve never had a source file lag issue after pushing updates, whether on my phone or desktop, and without using force reload.

I do like the feature suggestion though, I’m just unsure of how necessary it is when we are usually implementing caching solutions, cloudflare, etc.

**Comment by Thomas-A-Reinert** [comment] 2018-04-15 01:55
Sorry, that I and maybe also @gintsmurans started it - but the whole discussion is pointless as a whole. And sorry - I added up to that and was _totally_ opinionated without going into details! Really - sorry. That should´ve been handled more professionally and less opinionated..

**To clarify:**
- What @gintsmurans suggested totally works. It busts cache when there´s an update. And a pretty smart resolution to it vs. the "theme version" resolution before which won´t get updated too often, I guess.
Sidenote: I guess it´s not already implemented in the child-theme, is it?
- What does a browser do with that information? If the _exact_ string/URL ain´t cached - reload or to be precise: "_load the NEW ressource_". So that´s what cache-busting is supposed to do, right?
- Does it have any impact on performance? Well, if you do not change your css every single minute - nope.
- Does it solve above mentioned "client-problems"? Yes, it DOES in fact!

**Conclusion:** Everything works as intended.

***BUT***
As I´m _trying_ (which definitely doesn´t work with daily "breadnbutter-business" to just adjust premade "multi-purpose" themes as "DIVI", "AVADA" and the likes) to offer "to-the-max"-optimized solutions to my clients there´s often need for discussion if I use query strings for static ressources as those get - for whatever reasons I don´t really care about - get penalized by several tools mentioned above.

Please check those UnderStrap-based-solutions for example: 

- https://gtmetrix.com/reports/www.onlineoper.de/2yR0lyQ3 that loads <1 sec (even without gzip-Compression! ON A WORDPRESS SITE!!!) and
- https://gtmetrix.com/reports/www.oakbeardcare.com/EV3UGcOT which is a HEAVILY customized solution with UnderStrap / SiteOrigin Pagebuilder and many, many more tweaks that loads <3 sec and has a fullscreen header slider with 5+ items.

Yes, I know there are still ways to improve ´em (And i´d be happy if you could mention any improvements!). But they´re not finally optimized at all, so I don´t give flying f*ck about it, they´re performing _pretty_ well.
But testing my solutions against virtually _any_ testing-environment is crucial for jobs. Anything that contradicts is a NO-GO! And: Hard to explain, no matter the circumstances.

To be explicit: we´re not talking about the usual John-Doe as a client, who probably wouldn´t care/know anyway, but medium-sized to enterprise clients.

**Conclusion:** It does _not_  impact performance at all! It just depends on the performance-testing tools. And well, yes, they´re giving you a worse scoring if you use static files with a query string!

@ZacharyElkins is _ABSOLUTELY_ right: Performance-oriented site will prolly always use some kind of caching. Be it "Autoptimize" for the lower-level or "Lazy load", "W3 Cache"and the likes for a higher-level performance-optimization that will also get rid of versioning. But I won´t get into that for details....

**Final Question is**: Do we want to get rid of dev-problems (as I mentioned above, if a Dev is not capable enough to find a workaround - get rid of him!) or is a dev not capabable to setup a decent non-caching environment through W3C and the likes (Still: get rid of him!) or is the end-user not being able to be able to be taught to force-reload? If the latter is the case, the customer will probably never ever find the cause for performance anyway. Leave it as it is then.

**Comment by gintsmurans** [comment] 2018-04-15 08:34
@holger1411 This is so familiar :) I also find that cache expiration headers are not always working and this is, as you say, a "hard browser cache reset", that works. Whats the point of having good performance, if customers see the website as not intended..

**Comment by 0dp** [comment] 2018-04-15 14:09
Does that not mean that if we want to satisfy everybody. We will need to drop the query string in favor of rewriting the source name when compiling a new version, and injecting the new version.
That is, `...style.[value].min.css` in favor of `...style.min.css?v=[value]`

**Comment by Thomas-A-Reinert** [comment] 2018-04-16 02:29
@0dp : yes, that´s absolutely it and the smartest solution by far in my eyes. Not easy to implement though, I guess.  And no - I absolutely have _no_ clue about how to realize that.

@gintsmurans : My suggestion should solve your problem too, right? Yes I understand your concerns. Totally. It´s non-web-educated customers vs. too-well-educated customers.
@holger1411 : it would also solve your problem with clients and multiple iterations per day.

I will set up a testing scenario in the next days to find out which impact it has, okay? Until then I´d suggest to leave thing as they are now. Because other approach _will_ have any disadvantages that can easily be solved by either taking actions by the dev or teaching the client.

**Comment by 0dp** [comment] 2018-04-16 06:49
We can make it happen with gulp-rev in the dist task, and a small addition to enqueue.php

**Comment by Thomas-A-Reinert** [comment] 2018-04-16 23:26
@0dp you don´t only have my thumbs but also my big toes up for that ;)

**Comment by 0dp** [comment] 2018-04-17 06:58
I can write up a glob for that to test out

**Comment by 0dp** [comment] 2018-04-26 20:48
Ohh damn, I forgot I was writing this up. I'm off tomorrow hopefully I can finish up a test

**Comment by 0dp** [comment] 2018-05-02 10:30
^^^^WOOP WOOP^^^^
Please test this, but it seems to work smooth as butter.

Had to close the other PR cuz it was a sloppy mess

**Comment by Thomas-A-Reinert** [comment] 2018-06-06 02:08
As noone complained by now and personally can confirm this - going to close that on.

But as that´s a core-performance thingie .. feel free to re-open this issue and/or contribute!

**Closed by Thomas-A-Reinert** 2018-06-06 02:08 UTC
