### ISSUE TITLE
gulpfile TLC

### ISSUE THREAD

**Issue by 0dp** [understrap/understrap#560] opened 2018-02-19 13:02 UTC
It looks like the gulpfile still needs a bit of TLC #252. Travis pukes every time a new PR is made.
Either a refactoring or some rules in the travis config.

I made a few test PRs
#558 #559

**Comment by Thomas-A-Reinert** [comment] 2018-03-02 21:35
Yes, i´m a bit further now, digging a bit deeper into the whole issue.
Seems travis-ci would not only check the pull-requests itself (treated as a snippet) but the WHOLE thingie..

And that´s where the gulpfile seems to have issues. See https://travis-ci.org/understrap/understrap/jobs/348303707 for example. This should be easily fixable.

**Comment by 0dp** [comment] 2018-03-03 13:15
I might be wrong, it just looks like the evaluation of the gulp file is a bit hysterical? If you look at the theater PRs I made it just keeps going

**Comment by IngoVals** [comment] 2018-03-04 11:45
> Seems travis-ci would not only check the pull-requests itself (treated as a snippet) but the WHOLE thingie.

I would say that is a preferred behaviour to ensure a PR isn't breaking something at another place in the project. This however seems highly unlikely in the case of a Wordpress theme as opposed to a big OOP project.

Its all about maintaining the unit tests and here it seems that the Travis test has some rules on how javascript files should be formatted that the `gulpfile.js` is breaking. So we should fix the gulpfile or change the rules.

**Comment by 0dp** [comment] 2018-03-04 14:43
@IngoVals so in terms of the gulp file, what would be the best way to change the rules for the gulpfile to be, lets called it, less conservative?

**Comment by IngoVals** [comment] 2018-03-04 18:58
Sadly I'm not familiar with the process, but it seems this is just default _jscs_ behaviour and probably would need a config file. Did your pull requests not fix the issue?

**Comment by 0dp** [comment] 2018-03-04 20:13
No it kept maxing out the error log, to the point it just seemed redundant to the point where I was adding spaces everywhere. But maybe that is just me

**Comment by IngoVals** [comment] 2018-03-04 20:44
Ok I looked a bit into this. The _jscs_ that seems to be generating most of the errors is using a wordpress preset and it is set in the `.jscsrc` file. Since the _gulpfile_ isn't ran in the _wordpress_ environment and is more used in the development process for the theme we could add it to the `excludedFiles` array and ignore the wordpress requirements for that file.

If that isn't acceptable I guess we could just install and run _jscs_ locally and remove the limit and find each and every issue and fix it in a PR and hope that it works. In the future we would then require all PR's to fulfill the _travis_ tests.

**Comment by IngoVals** [comment] 2018-03-04 20:56
Ran this in the project `jscs . --max-errors Infinity` and there are 526 errors, all but 3 of them in the gulpfile.

1 each in 

- ./js/customizer.js
- ./js/navigation.js
- ./js/skip-link-focus-fix.js

Invalid break ones. I could run through the gulpfile and see if the fixing isn't just a easy "add spaces, remove commas" type of deal but that would have to wait until tomorrow.

**Comment by 0dp** [comment] 2018-03-04 22:19
I ran the same command on the gulpfile alone, reported : 1044 code style errors found. That's a lot of "add spaces, remove commas" 😉

**Comment by axlright** [comment] 2018-03-05 16:26
Wow - 1044 code style errors for a file that is 339 lines long? Crazy. I don't write js enough to weigh in on fixes but that's staggering...

**Comment by IngoVals** [comment] 2018-03-05 17:40
I find it strange that @0dp found more errors than I did, I just forked the master branch during the weekend I think, what version are you using?

I think excluding the gulpfile should be a go to strategy for now and we can decide on code standards for that later on. At the same time I think some of the errors might be fixed right away, missing semicolons and so on.

**Comment by 0dp** [comment] 2018-03-05 18:27
@IngoVals a cloned the repo right after I saw your post. 

Anyways, I'm down to 4 errors

```
odp:understrap odp$ jscs . --max-errors Infinity gulpfile.js
requireVarDeclFirst: Variable declarations must be the first statements of a function scope. at ./gulpfile.js :
   245 |// Copy all Font Awesome Fonts
   246 |
   247 |    var stream = gulp.src( paths.node + 'font-awesome/fonts/**/*.{ttf,woff,woff2,eof,svg}' )
------------^
   248 |        .pipe( gulp.dest( './fonts' ) );
   249 |

requireYodaConditions: Not yoda condition at ./gulpfile.js :
   280 |
   281 |gulp.task( 'clean-vendor-assets', function( ) {
   282 |  return del( [paths.dev + '/js/bootstrap4/**', paths.dev + '/sass/bootstrap4/**', './fonts/*wesome*.{ttf,woff,woff2,eof,svg}', paths.dev + '/sass/fontawesome/**', paths.dev + '/sass/underscores/**', paths.dev + '/js/skip-link-focus-fix.js', paths.js + '/**/skip-link-focus-fix.js', paths.js + '/**/popper.min.js', paths.js + '/**/popper.js', ( paths.vendor !=  '' ? ( paths.js + paths.vendor + '/**' ) : '' )]);
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------^
   283 |});
   284 |

requireVarDeclFirst: Variable declarations must be the first statements of a function scope. at gulpfile.js :
   245 |// Copy all Font Awesome Fonts
   246 |
   247 |    var stream = gulp.src( paths.node + 'font-awesome/fonts/**/*.{ttf,woff,woff2,eof,svg}' )
------------^
   248 |        .pipe( gulp.dest( './fonts' ) );
   249 |

requireYodaConditions: Not yoda condition at gulpfile.js :
   280 |
   281 |gulp.task( 'clean-vendor-assets', function( ) {
   282 |  return del( [paths.dev + '/js/bootstrap4/**', paths.dev + '/sass/bootstrap4/**', './fonts/*wesome*.{ttf,woff,woff2,eof,svg}', paths.dev + '/sass/fontawesome/**', paths.dev + '/sass/underscores/**', paths.dev + '/js/skip-link-focus-fix.js', paths.js + '/**/skip-link-focus-fix.js', paths.js + '/**/popper.min.js', paths.js + '/**/popper.js', ( paths.vendor !=  '' ? ( paths.js + paths.vendor + '/**' ) : '' )]);
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------^
   283 |});
   284 |
```

gulpfile to test
```
// Defining requirements

var gulp = require( 'gulp' );
var plumber = require( 'gulp-plumber' );
var sass = require( 'gulp-sass' );
var watch = require( 'gulp-watch' );
var cssnano = require( 'gulp-cssnano' );
var rename = require( 'gulp-rename' );
var concat = require( 'gulp-concat' );
var uglify = require( 'gulp-uglify' );
var merge2 = require( 'merge2' );
var imagemin = require( 'gulp-imagemin' );
var ignore = require( 'gulp-ignore' );
var rimraf = require( 'gulp-rimraf' );
var clone = require( 'gulp-clone' );
var merge = require( 'gulp-merge' );
var sourcemaps = require( 'gulp-sourcemaps' );
var browserSync = require( 'browser-sync' ).create( );
var del = require( 'del' );
var cleanCSS = require( 'gulp-clean-css' );
var gulpSequence = require( 'gulp-sequence' );
var replace = require( 'gulp-replace' );
var autoprefixer = require( 'gulp-autoprefixer' );

// Configuration file to keep your code DRY

var cfg = require( './gulpconfig.json' );
var paths = cfg.paths;

// Run:
// gulp sass + cssnano + rename
// Prepare the min.css for production (with 2 pipes to be sure that "theme.css" == "theme.min.css")

gulp.task( 'scss-for-prod', function( ) {
    var source =  gulp.src( paths.sass + '/*.scss' )
        .pipe( plumber({
            errorHandler: function( err ) {
                console.log( err );
                this.emit( 'end' );
            }
        } ) )
        .pipe( sourcemaps.init({ loadMaps: true } ) )
        .pipe( sass(  ) );

    var pipe1 = source.pipe( clone(  ) )
        .pipe( sourcemaps.write( undefined, { sourceRoot: null } ) )
        .pipe( gulp.dest( paths.css ) )
        .pipe( rename( 'custom-editor-style.css'  ) );

    var pipe2 = source.pipe( clone(  ) )
        .pipe( minify(  ) )
        .pipe( rename({ suffix: '.min' } ) )
        .pipe( gulp.dest( paths.css ) );

    return merge( pipe1, pipe2 );
});

// Run:
// gulp sourcemaps + sass + reload(browserSync)
// Prepare the child-theme.css for the development environment

gulp.task( 'scss-for-dev', function( ) {
    gulp.src( paths.sass + '/*.scss' )
        .pipe( plumber({
            errorHandler: function( err ) {
                console.log( err );
                this.emit( 'end' );
            }
        } ) )
        .pipe( sourcemaps.init({ loadMaps: true } ) )
        .pipe( sass(  ) )
        .pipe( sourcemaps.write( undefined, { sourceRoot: null } ) )
        .pipe( gulp.dest( paths.css ) );
});

gulp.task( 'watch-scss', ['browser-sync'], function( ) {
    gulp.watch( paths.sass + '/**/*.scss', ['scss-for-dev']);
});

// Run:
// gulp sass
// Compiles SCSS files in CSS

gulp.task( 'sass', function( ) {
    var stream = gulp.src( paths.sass + '/*.scss' )
        .pipe( plumber({
            errorHandler: function( err ) {
                console.log( err );
                this.emit( 'end' );
            }
        } ) )
        .pipe( sass(  ) )
        .pipe( autoprefixer( 'last 2 versions'  ) )
        .pipe( gulp.dest( paths.css ) )
        .pipe( rename( 'custom-editor-style.css'  ) );
    return stream;
});

// Run:
// gulp watch
// Starts watcher. Watcher runs gulp sass task on changes

gulp.task( 'watch', function( ) {
    gulp.watch( paths.sass + '/**/*.scss', ['styles']);
    gulp.watch( [paths.dev + '/js/**/*.js', 'js/**/*.js', '!js/theme.js', '!js/theme.min.js'], ['scripts'] );

    //Inside the watch task.
    gulp.watch( paths.imgsrc + '/**', ['imagemin-watch']);
});

/**
 * Ensures the 'imagemin' task is complete before reloading browsers
 * @verbose
 */

gulp.task( 'imagemin-watch', ['imagemin'], function( done ) {
  browserSync.reload( );
  done( );
});

// Run:
// gulp imagemin
// Running image optimizing task

gulp.task( 'imagemin', function( ) {
    gulp.src( paths.imgsrc + '/**' )
    .pipe( imagemin(  ) )
    .pipe( gulp.dest( paths.img ) );
});

// Run:
// gulp cssnano
// Minifies CSS files

gulp.task( 'cssnano', function( ) {
  return gulp.src( paths.css + '/theme.css' )
    .pipe( sourcemaps.init({ loadMaps: true } ) )
    .pipe( plumber({
            errorHandler: function( err ) {
                console.log( err );
                this.emit( 'end' );
            }
        } ) )
    .pipe( rename({ suffix: '.min' } ) )
    .pipe( cssnano({ discardComments: { removeAll: true } } ) )
    .pipe( sourcemaps.write( './'  ) )
    .pipe( gulp.dest( paths.css ) );
});

gulp.task( 'minify', function( ) {
  return gulp.src( paths.css + '/theme.css' )
  .pipe( sourcemaps.init({ loadMaps: true } ) )
    .pipe( cleanCSS({ compatibility: '*' } ) )
    .pipe( plumber({
            errorHandler: function( err ) {
                console.log( err );
                this.emit( 'end' );
            }
        } ) )
    .pipe( rename({ suffix: '.min' } ) )
     .pipe( sourcemaps.write( './'  ) )
    .pipe( gulp.dest( paths.css ) );
});

gulp.task( 'cleancss', function( ) {
  return gulp.src( paths.css + '/*.min.css', { read: false }) // Much faster
    .pipe( ignore( 'theme.css'  ) )
    .pipe( rimraf(  ) );
});

gulp.task( 'styles', function( callback ) {
    gulpSequence( 'sass', 'minify' )( callback );
});

// Run:
// gulp browser-sync
// Starts browser-sync task for starting the server.

gulp.task( 'browser-sync', function( ) {
    browserSync.init( cfg.browserSyncWatchFiles, cfg.browserSyncOptions );
});

// Run:
// gulp watch-bs
// Starts watcher with browser-sync. Browser-sync reloads page automatically on your browser

gulp.task( 'watch-bs', ['browser-sync', 'watch', 'scripts'], function( ) {

});

// Run:
// gulp scripts.
// Uglifies and concat all JS files into one

gulp.task( 'scripts', function( ) {
    var scripts = [

        // Start - All BS4 stuff

        paths.dev + '/js/bootstrap4/bootstrap.js',

        // End - All BS4 stuff

        paths.dev + '/js/skip-link-focus-fix.js'
    ];
  gulp.src( scripts )
    .pipe( concat( 'theme.min.js' ) )
    .pipe( uglify( ) )
    .pipe( gulp.dest( paths.js ) );

  gulp.src( scripts )
    .pipe( concat( 'theme.js' ) )
    .pipe( gulp.dest( paths.js ) );
});

// Deleting any file inside the /src folder

gulp.task( 'clean-source', function( ) {
  return del( ['src/**/*'] );
});

// Run:
// gulp copy-assets.
// Copy all needed dependency assets files from bower_component assets to themes /js, /scss and /fonts folder. Run this task after bower install or bower update

////////////////// All Bootstrap SASS  Assets /////////////////////////

gulp.task( 'copy-assets', function( ) {

////////////////// All Bootstrap 4 Assets /////////////////////////

// Copy all JS files

    var stream = gulp.src( paths.node + 'bootstrap/dist/js/**/*.js' )
        .pipe( gulp.dest( paths.dev + '/js/bootstrap4' ) );

// Copy all Bootstrap SCSS files

    gulp.src( paths.node + 'bootstrap/scss/**/*.scss' )
        .pipe( gulp.dest( paths.dev + '/sass/bootstrap4' ) );
    return stream;

////////////////// End Bootstrap 4 Assets /////////////////////////

// Copy all Font Awesome Fonts

    var stream = gulp.src( paths.node + 'font-awesome/fonts/**/*.{ttf,woff,woff2,eof,svg}' )
        .pipe( gulp.dest( './fonts' ) );

// Copy all Font Awesome SCSS files

    gulp.src( paths.node + 'font-awesome/scss/*.scss' )
        .pipe( gulp.dest( paths.dev + '/sass/fontawesome' ) );

// _s SCSS files

    gulp.src( paths.node + 'undescores-for-npm/sass/media/*.scss' )
        .pipe( gulp.dest( paths.dev + '/sass/underscores' ) );

// _s JS files into /src/js

    gulp.src( paths.node + 'undescores-for-npm/js/skip-link-focus-fix.js' )
        .pipe( gulp.dest( paths.dev + '/js' ) );

// _s JS files into /js

    gulp.src( paths.node + 'undescores-for-npm/js/skip-link-focus-fix.js' )
        .pipe( gulp.dest( paths.js + paths.vendor ) );

// Copy Popper JS files

    gulp.src( paths.node + 'popper.js/dist/umd/popper.min.js' )
        .pipe( gulp.dest( paths.js + paths.vendor ) );
    gulp.src( paths.node + 'popper.js/dist/umd/popper.js' )
        .pipe( gulp.dest( paths.js + paths.vendor ) );
    return stream;
});

// Deleting the files distributed by the copy-assets task

gulp.task( 'clean-vendor-assets', function( ) {
  return del( [paths.dev + '/js/bootstrap4/**', paths.dev + '/sass/bootstrap4/**', './fonts/*wesome*.{ttf,woff,woff2,eof,svg}', paths.dev + '/sass/fontawesome/**', paths.dev + '/sass/underscores/**', paths.dev + '/js/skip-link-focus-fix.js', paths.js + '/**/skip-link-focus-fix.js', paths.js + '/**/popper.min.js', paths.js + '/**/popper.js', ( paths.vendor !=  '' ? ( paths.js + paths.vendor + '/**' ) : '' )]);
});

// Run
// gulp dist
// Copies the files to the /dist folder for distribution as simple theme

gulp.task( 'dist', ['clean-dist'], function( ) {
  return gulp.src( ['**/*', '!' + paths.bower, '!' + paths.bower + '/**', '!' + paths.node, '!' + paths.node + '/**', '!' + paths.dev, '!' + paths.dev + '/**', '!' + paths.dist, '!' + paths.dist + '/**', '!' + paths.distprod, '!' + paths.distprod + '/**', '!' + paths.sass, '!' + paths.sass + '/**', '!readme.txt', '!readme.md', '!package.json', '!package-lock.json', '!gulpfile.js', '!gulpconfig.json', '!CHANGELOG.md', '!.travis.yml', '!jshintignore',  '!codesniffer.ruleset.xml',  '*'], { 'buffer': false })
  .pipe( replace( '/js/jquery.slim.min.js', '/js' + paths.vendor + '/jquery.slim.min.js', { 'skipBinary': true } ) )
  .pipe( replace( '/js/popper.min.js', '/js' + paths.vendor + '/popper.min.js', { 'skipBinary': true } ) )
  .pipe( replace( '/js/skip-link-focus-fix.js', '/js' + paths.vendor + '/skip-link-focus-fix.js', { 'skipBinary': true } ) )
    .pipe( gulp.dest( paths.dist ) );
});

// Deleting any file inside the /dist folder

gulp.task( 'clean-dist', function( ) {
  return del([paths.dist + '/**']);
});

// Run
// gulp dist-product
// Copies the files to the /dist-prod folder for distribution as theme with all assets

gulp.task( 'dist-product', ['clean-dist-product'], function( ) {
  return gulp.src(['**/*', '!' + paths.bower, '!' + paths.bower + '/**', '!' + paths.node, '!' + paths.node + '/**', '!' + paths.dist, '!' + paths.dist + '/**', '!' + paths.distprod, '!' + paths.distprod + '/**', '*'])
    .pipe( gulp.dest( paths.distprod ) );
});

// Deleting any file inside the /dist-product folder

gulp.task( 'clean-dist-product', function( ) {
  return del([paths.distprod + '/**']);
});
```

**Comment by 0dp** [comment] 2018-03-05 19:03
I just read through the JSCS docs, and it's possible to include rules in the top of specific files
```
// jscs:disable requireVarDeclFirst
// jscs:disable requireYodaConditions
```
Could be an option?

**Comment by IngoVals** [comment] 2018-03-06 09:00
You seem to get a duplicate of each error, would explain why you got twice the problems I got

Yoda can be fixed by just doing `( paths.vendor !=  '' ?` => `( '' != paths.vendor ?`.

I have a bit of a problem with the other one. It seems that the _copy-asset_ task has a non conditional return very early on. What am I missing? Does the _copy-asset_ task actually work as intended?

**Comment by 0dp** [comment] 2018-03-06 10:25
@IngoVals copy-assests does not work as intended I have made a patch here #589 with steps to reproduce

**Comment by holger1411** [comment] 2018-03-07 12:44
After fixing 100+ "errors" (<- everything works, its just to beautify the code) or so I add /gulpfile.js to the .jscsrc and .jshint ignore list

I agree with @IngoVals and the rest of you: Travis should help us to ensure that the wordpress .php files are using the WordPress coding standards. Not more not lee.
If the Travis log constantly produces hunderets of error message no one will take care of any integration notice.

So build #396 is now green 🎉 
https://travis-ci.org/understrap/understrap

**Comment by holger1411** [comment] 2018-03-07 12:46
Close this but feel free to re-open it if neccessary

**Closed by holger1411** 2018-03-07 12:46 UTC
