### ISSUE TITLE
NPM install fails due to permissions errors and failed directory creation

### ISSUE THREAD

**Issue by nizz0k** [understrap/understrap#591] opened 2018-03-08 13:42 UTC
So, I'm just getting started with Understrap on a Linux Subsystem on Windows localhost setup. Node works fine, but running "npm install" from the theme folder produces the following errors:

```
npm WARN deprecated gulp-util@2.2.20: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN bootstrap@4.0.0 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm ERR! path /var/www/html/dml-uganda.org/wp-content/themes/understrap/node_modules/bs-recipes
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/var/www/html/dml-uganda.org/wp-content/themes/understrap/node_modules/bs-recipes' -> '/var/www/html/dml-uganda.org/wp-content/themes/understrap/node_modules/.bs-recipes.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.`
```
I've read the medium post on how to fix this, but my only gulp-util dependency is gulp itself, so not sure how proceed here. Sorry for being a noob.

**Comment by 0dp** [comment] 2018-03-08 16:16
Hi @nizz0k 

> `npm ERR! enoent This is related to npm not being able to find a file.`

is `var/www/html/dml-uganda.org/` the correct path for your installation?

**Comment by nizz0k** [comment] 2018-03-09 09:39
Hi @Odp, thanks for your answer. Yes, the path is correct for the wordpress root. the understrap folder is nested a few folders further. I tried installing from the website and uploading the folders, now I'm trying with just npm

**Comment by nizz0k** [comment] 2018-03-09 12:10
So, I've been testing different approaches, and it might be a weird WSSL node issue, as I seem to get "EACCES" errors as well. The file path is correct, but the folders the script is trying to find don't exist.

**Comment by holger1411** [comment] 2018-03-11 15:50
@nizz0k Which node and npm version do you use?
Find a lot of issues with the same/similiar errore message on Windows PC´s and the solution was always to up- or downgrade npm...

**Comment by nizz0k** [comment] 2018-03-11 16:49
@holger1411 I'm running node 8.9.4 and npm 5.6.0. I guess I can try to systematically roll back, or is there a version you'd recommend?

**Comment by holger1411** [comment] 2018-03-11 19:58
Hm, I have no experience on Windows systems. 
But I use node: '6.9.1' currently. Very oldschool I know. But I can confirm that it works here.
@all Anyone else here with the same/similar problem?

**Comment by 0dp** [comment] 2018-03-21 15:56
@nizz0x, could you maybe test with the node version you get with the windows installer found here: https://nodejs.org/en/download/

**Comment by nizz0k** [comment] 2018-03-23 12:19
Hi, sorry to the delay in responding. I think the issue is some sort of permissions/config issue on the Linux Subsystem for Windows. I don't seem to have any node issues in the actual Windows file system. I'll experiment with setting up and xammp based localhost and see if this solves the problem.

**Comment by 0dp** [comment] 2018-03-24 10:31
Hi @nizz0k, It would be interesting to see what you come up with. I can't test my self since I don't have a windows box.

Whats the output of `npm -v` ?

**Comment by nizz0k** [comment] 2018-03-26 08:00
On the regular windows 10 filesystem it's NPM 5.5.1, the Ubuntu windows subsystem it's 5.6.0.

**Comment by 0dp** [comment] 2018-03-26 08:06
You don't get any errors when you check the version on sub system?

**Comment by nizz0k** [comment] 2018-03-26 08:56
So, no errors when running `npm -v` in either the Linux Subsystem or in the regular file system. Installation seems to proceed fine with warning about dependencies and installs 1162 packages on the windows. It appears to install correctly

**Comment by 0dp** [comment] 2018-03-26 12:03
Ok, what happens if you run bash as administrator (is that possible)

**Comment by nizz0k** [comment] 2018-03-26 12:16
Running Ubuntu as admin still produced EACCESS errors. Same with trying to run npm with sudo

**Comment by 0dp** [comment] 2018-03-26 20:40
have you checked your PATH

**Comment by Thomas-A-Reinert** [comment] 2018-05-26 23:44
Has this been solved by now? After two months of no replies, I´ll close this issue. Feel free to reopen, if the problem still persists!

**Closed by Thomas-A-Reinert** 2018-05-26 23:44 UTC
