### ISSUE TITLE
Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'bp_activity_reset_my_new_mentions' not found or invalid function name in C:\xampp\htdocs\dryv\wp-includes\class-wp-hook.php on line 286

### ISSUE THREAD

**Issue by jerryon92** [understrap/understrap#706] opened 2018-06-06 23:47 UTC
Please delete anything that does not apply for you!

## Issue is about..
  - [ ] a Bug Report
  - [ ] a Feature Request
  - [ ] a Suggestion
  - [ ] a Question
  - [ ] I need help

## Please tell us about your environment:

  - **WordPress Version:** 4.9.x
  - **OS Version:** [Windows 7 | Windows 8 | Windows 10] | Linux [Distribution / Version] | MacOS [Version] | Android [Version] | iOS [Version]
  - **Browser:** [ all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
  - **Language:** [ all | PHP | SQL | HTML | S/CSS | Javascript | jQuery | ES6 | JSON | XML]
  - **Node.js & NPM Versions:** Node.js [V X.XX] | NPM [V X.XX]

---

# Issue Overview for Bugreports

## Expected behavior

# Todos

 * Test
 * Documentation

**Comment by jerryon92** [comment] 2018-06-06 23:50
Hi.

I am building a community site and I came across this error.

Can someone help me fix it?

Please be as basic as possible because I am new to wordpress. I do not know how to code

**Comment by ZacharyElkins** [comment] 2018-06-07 01:17
Hi @jerryon92 

First, I must say that this is something that would be better asked at StackOverflow. I recommend searching there for this error, as there is a lot written about it already. Google will produce a lot of reading as well. So, in short, this isn't an Understrap issue, nor is this really the appropriate place for these questions.

That aside, this is likely being caused by a plugin. If you are writing PHP into your site, then that could produce these errors as well.

1. Check to see what version of PHP you are using, and also run a plugin compatibility check of that version of PHP. (I recommend PHP 7.1 if your plugins support it, or at least 7.0)
2. Deactivate all your plugins and see if it is still throwing the error.
3. If the error is gone, reactivate plugins 1 by 1 until you find the culprit. If not, skip to #5
4. Consider using a different plugin, or search for the error with that plugin specifically.
5. If you still see the error with all plugins deactivated, change your theme to TwentyEighteen or some other Wordpress default and check for the error.
6. If still seeing an error, check the directory `wp-content/mu-plugins`, there may be a plugin there that is causing it. This is the "must use" folder, and sometimes hosting providers add stuff here.

9/10 times it is a plugin, especially if you haven't added custom PHP.

**Comment by Thomas-A-Reinert** [comment] 2018-06-07 02:46
I agree - totally not UnderStrap related. 
`function 'bp_activity_reset_my_new_mentions'` totally sound like a buddypress function.

Closing this issue.

**Closed by Thomas-A-Reinert** 2018-06-07 02:46 UTC
