### ISSUE TITLE
Override files in /inc folder?

### ISSUE THREAD

**Issue by evandiamond** [understrap/understrap#376] opened 2017-07-30 01:59 UTC
@holger1411 Hey bud, is it possibly to override the files in this folder so I can create new functions? I tried duplicating the folder and changing this `require get_template_directory() . '/inc/theme-settings.php';` to the `get_stylesheet_directory_uri` directory, but that didn't help :(

I was able to override them in the functions.php file, but I wanted to keep everything organized!

Cheers.

**Comment by netzkaefer** [comment] 2017-09-01 09:49
Hi,

isn´t it possible to wrap all function in the understrap inc files (and mybe in other files too) with:

if( !function_exists('understrap_function_name') ) ...

So it´s easy to overwrite them in Child themes.

cheers

**Comment by axlright** [comment] 2018-04-04 14:35
Closing this issue as it is a duplicate of #550 and was patched in PR #619

**Closed by axlright** 2018-04-04 14:35 UTC
