### ISSUE TITLE
Pagination doesn't work

### ISSUE THREAD

**Issue by sol-idsnake** [understrap/understrap#1039] opened 2019-09-26 20:24 UTC
Please delete anything that does not apply for you!

## Issue is about..
  - [X] a Bug Report
  - [ ] a Feature Request
  - [ ] a Suggestion
  - [ ] a Question
  - [ ] I need help

## Please tell us about your environment:

  - **WordPress Version:** 5.2.3
  - **OS Version:** [Windows 10]
  - **Browser:** [ all ]
  - **Language:** [ PHP ]

---
I am looking to implement the basic pagination featured in understrap:

`       $paged = ( get_query_var( 'paged' ) ) ? get_query_var( 'paged' ) : 1;`

	$comp_news_args = array(
		'post_type'	=>	'comp',
		'posts_per_page'    => 3,
		'paged'    => $paged,
		'orderby'   => 'ID',
		'order'     => 'DESC'	
	);
	$comp_news = new WP_Query( $comp_news_args );

I have not changed the custom pagination function that ships with understrap.
Then I'm calling `understrap_pagination()`. 

Nothing happens. I see the number of posts limited to 3, but no pagination buttons appear anywhere.
Am I missing anything?

**Comment by 0dp** [comment] 2019-09-26 20:34
I can see you're working with a custom post type.
So i believe the pagination works if you use WordPress' default posts via archive.php
Could you please verify?

**Comment by phoshenwen** [comment] 2019-09-27 11:22
My steps:
Fresh install of Understrap
Create 3 posts under WP native Posts (no custom post type on test, will confirm with custom post type later)
Args I ran: 
		'post-type'=>'post',
		'posts_per_page' => 2,
		'paged'=>$paged

plus: $paged = ( get_query_var( 'paged' ) ) ? get_query_var( 'paged' ) : 1;

All this via archive.php, were understrap_pagination() has already been entered out of the box.

Does not work

**Comment by sol-idsnake** [comment] 2019-09-27 13:56
My steps:
Fresh install of Understrap
Create 3 posts under WP native Posts (no custom post type on test, will confirm with custom post type later)
Args I ran:
'post-type'=>'post',
'posts_per_page' => 2,
'paged'=>$paged

plus: $paged = ( get_query_var( 'paged' ) ) ? get_query_var( 'paged' ) : 1;

All this via archive.php, were understrap_pagination() has already been entered out of the box.

Does not work

**Comment by 0dp** [comment] 2019-09-27 15:19
Ok, I see what your doing.

If instead of making a custom loop, use the_loop() so use the standard archive function in WordPress. Designate a page to be your blog page under settings.

You should see the pagination works.

If this is the case we have to look at how you are implementing your custom loops

**Comment by Thomas-A-Reinert** [comment] 2019-09-27 22:58
It would help if you´d paste the COMPLETE code of your file and it´s name/location/implementation so that we´d be able to reproduce it. Thanks for putting up some info, but still – we´d need to reproduce some steps.

Remember: We´re totally voluntary doing that "job" - so anything to simplify things for us is recommended. At least if you want to get an answer FAST ;)

**Comment by Beaniie** [comment] 2019-10-29 13:32
I don't mean to hijack; but I'm running into the same issue. Here's the code and its location;
`File: in [page-templates]`
`Assigned to wp-page [latest-articles]` 
`File name: latest-articles.php`

Note: `understrap_pagination();` hasn't been modified.

Thanks again,
-B.

```html
<div class="bg-light">
  <div class="container space-top-3 space-bottom-2">
    <div class="row">
      <?php $paged = ( get_query_var( 'paged' ) ) ? get_query_var( 'paged' ) : 1;
      $args = array(
       'post_type' => 'post',
       'orderby' => 'post_date',
       'order' => 'desc',
       'perm' => 'readable',
       'show_post_views' => true,
       'posts_per_page' => 9,
       'paged' => $paged
      ); ?>
      <?php $latestArticles = new WP_Query( $args ); ?>
      <?php if ( $latestArticles->have_posts() ) : ?>
          <?php /* Start the Loop */ ?>
          <?php while ( $latestArticles->have_posts() ) : $latestArticles->the_post(); ?>
            <?php get_template_part( 'loop-templates/content-search', get_post_format() ); ?>
        <?php endwhile; ?>
    </div>

    <div class="row space-2">
      <pre>
	<?php print_r ($args); ?>
      </pre>
    </div>

    <div class="row mt-3">
      <div class="col-auto">
        <!-- The pagination component -->
        <?php understrap_pagination(); ?>
        <?php wp_reset_postdata(); ?>
      <?php endif; ?>
      </div>
    </div>
  </div>
</div>

**Comment by LukaszJaro** [comment] 2019-11-07 15:54
I had pagination issues as well when I was creating a custom search, the main thing that solved is "Replacing the main $wp_query object with the custom query object for pagination/results to work"

see below for sample:

```
global $wp_query;

                                // Get current page out of the current query, if available..if not set to 1.
                                $paged = get_query_var( 'paged' ) ? intval( get_query_var( 'paged' ) ) : 1;

                                // WP_Query arguments. Added defaults for performance.
                                $args = array(
                                    'post_type'      => array( 'any' ),
                                    'post_status'    => 'publish',
                                    'orderby'        => 'title',
                                    'order'          => 'ASC',
                                    's'              => sanitize_text_field( $_GET['search'] ), // Display posts that match the search term.
                                    'posts_per_page' => 10,
                                    'cache_results'  => false,
                                    'update_post_term_cache' => false,
                                    'update_post_meta_cache' => false,
                                    'paged'          => max( 1, $paged ),
                                );

                                // Custom Query.
                                $the_query = new WP_Query( $args );

                                // Replacing the main $wp_query object with the custom query object for pagination/results to work.
                                $wp_query = $the_query;

                                    // The Loop.
                                if ( $the_query->have_posts() ) { ...
```
don't forgot to wp_reset_postdata(); !

**Comment by IanDelMar** [comment] 2019-11-07 21:00
@Beaniie, you're trying to implement the pagination on a page, right? The pagination is meant for post pages such as index.php, archive.php, et cetera and therefore is working with the main query which on a page is a page query.
Check, for example, lines 15-17 in [pagination.php](https://github.com/understrap/understrap/blob/master/inc/pagination.php)
```php
if ( $GLOBALS['wp_query']->max_num_pages <= 1 ) {
	return;
}
```
`$GLOBALS['wp_query']` is the main query for the _page_! and ` $GLOBALS['wp_query']->max_num_pages` equals zero. The if statement evaluates to true and you are exiting `understrap_pagination()` at this point. However, removing those lines would not lead to the desired results as [`paginate_links()`](https://developer.wordpress.org/reference/functions/paginate_links/) also uses `$wp_query`. That's why @LukaszJaro 's example works - it alters the main query. Possibly the `wp_reset_postdata()` mentioned by @LukaszJaro should be complemented by `wp_reset_query()`.

I strongly suggest using your blog page for this where you usually find the latest articles anyway.

@sol-idsnake, can you elaborate on what you did? As far as I know, the archive page for the post type 'post' is the blog page. I installed the theme, checked the blog page, a category archive page, a tag archive page, a date archive page, and everything works just fine.

**Comment by Beaniie** [comment] 2019-11-11 10:47
@IanDelMar @LukaszJaro, you're both correct, it took me a little bit of time to understand how it was working along with a few questions but I was able to resolve my issue by making a small amendment to the `pagination.php` template while using the `child-theme`. You can see the fruits of my labour [here](https://github.com/understrap/understrap/issues/1054).

Thanks for the clarification. :)

**Comment by LukaszJaro** [comment] 2019-11-11 13:45
@Beaniie solution is most secure and performant, thanks for sharing!

**Comment by Thomas-A-Reinert** [comment] 2019-12-13 00:48
If the problem remains, please feel free to re-open that issue. I´ll close it for now since it seems to be solved if i´m not all wrong

**Closed by Thomas-A-Reinert** 2019-12-13 00:48 UTC

**Comment by IanDelMar** [comment] 2019-12-14 12:24
#1085

**Comment by anonimoconiglio** [comment] 2020-01-13 23:32
Thank you @LukaszJaro I just solved using this on my custom query:
> 'paged' => max( 1, $paged )

It is worth to point out that the `understrap_pagination();` function must be inside the loop, before the `wp_reset_postdata();`
