### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by Thomas-A-Reinert** [understrap/understrap#1089] opened 2019-12-17 01:02 UTC
## Issue is about..
  - [x] a Suggestion

## It would be cool to have a Roadmap for an upcoming release on WordPress.org.
For that we should have..

* Semantic versioning. If it´s not clear to  everyone what that means - let´s have a get-together with the core contributors. I maintain the Slack-channel, so that ain´t a problem at all to put us up to a certain standard.
* **BUGFIXES!** - There has never been an issue handling for really important bugs. But there SHOULD be. 
* **Feature Updates** - at least with my WCAG 2.1 Updates there´s a *lot* going to change for content contributors to make the document outline work well. That might work out well for anyone *without* updating, but it WILL work out a lot better for SEO etc. *when* you do. At least there´s a lot of possible optimizations that could be done. And *should* be done. At least for those taking care of – but they need to KNOW about it. A "ballon" within any update could take care of that.
* That should anyway happen with ANY update. To let users know what happened/changed. 
* Especially when there´s "breaking" updates
* The **documentation** should  be updated.
  * Sounds ridiculous: But the updated docs NEVER got published ANYWHERE. (and we put a f***cking sh*tload of work into it!)
  * Really, a straight FOCUS should be put on THAT! WHAT´s a framework without docs? SHIT.. Sorry. We could also get rid of a good amount of issues with that and/or take the most commented requests into it..
* @UnderstrapFramework : Just a personal note. I guess you already noticed that I got a problem with..
  * that RSS widget. That´s – my personal opinion – pretty obtrusive. Anyway, I can live with that in case it´s really helpful. Means: Change of content, not only "marketing". You´ll loose contributors if you keep it that way. And I guess you already seen how supportive we ("the community") are. Didn´t you?
  * An absolute NO-GO is that new admin main-menu entry for "OverStrap". GOSH, DUDE! THat´s TOTALLY obstrusive and an absolute NOGO. I cannot disable it, I do NOT want to have that for my clients and not even on a stock install. Go find another way for introducing your premium shizzle. But GET RID OF IT AT ONCE.

**Comment by gp0** [comment] 2019-12-17 01:38
> An absolute NO-GO is that new admin main-menu entry for "OverStrap". GOSH, DUDE! THat´s TOTALLY obstrusive and an absolute NOGO. I cannot disable it, I do NOT want to have that for my clients and not even on a stock install. Go find another way for introducing your premium shizzle. But GET RID OF IT AT ONCE.

+1 for that from an outside perspective, just did a fresh clone for a project and the first thing that is see is an admin menu with a nagscreen? Oof.

The commit adding it seems to be [this one](https://github.com/understrap/understrap/commit/9af15d7b119f5fafb848963281a9297ca2da3d32)

In addition it pulls in some kind of analytics bullshit:

`<iframe src="https://understrap.com/overstrap/?wp=1" id="inv_os_analytics"></iframe>`

The code also looks well, not exactly trust-building, e.g. throws warnings (seriously?):

`Notice: Undefined index: tab`

here: 

`function understrap_overstrap_page() {
  add_thickbox();
  $active_tab = $_GET[ 'tab' ];
  if($active_tab == ''){$active_tab = 'featured';}
?>`

$active_tab is then.. never used? What?

**Comment by IanDelMar** [comment] 2019-12-17 01:46
@semantic versioning: Yes! And let’s get rid of the annoying sidebar checks for UnderStrap 1.0.0!

@marketing overstrap: My 2
cents - I think a “theme settings” page with helpful resources (eg links to this repository and the documentation, etc) and recommended stuff (eg the free child theme and the OverStrap thing would be sufficient marketing. People will most likely not get annoyed because there is also actual useful stuff provided. In
case the feed is a must, we could offer a disable option there as well. @UnderstrapFramework check how Yoast was bashed for their aggressive black Friday marketing strategy. Ppl don’t like stuff like that. In fact you force each user/dev to use a child theme to just disable the feed and the menu.

@analytics: WTF! I just removed GA from this repository. I was not aware that I got tracked from my very first day here. Is this shit even GDPR compliant?

**Comment by noelspringer** [comment] 2019-12-17 02:41
> check how Yoast was bashed for their aggressive black Friday marketing strategy. **_Ppl don’t like stuff like that._**

+1

And yes, the `inc/wp-admin.php` file is where the Overstrap meta-box and menu item have been added.

**Comment by pattonwebz** [comment] 2019-12-17 09:50
Opened some issues about the tracking, new page, dashboard widget etc.

**Comment by UnderstrapFramework** [comment] 2019-12-17 10:23
The GA and the random useless code (not sure how I copied that) have been removed

a more helpful page with links to a help questions & answers section (which is next on my to do list) would be great for the 1.0 release

the RSS widget can be minimized as well, it does have some useful content come up but my recent efforts have been on marketing

what documentation are you talking about @Thomas-A-Reinert?

**Comment by pattonwebz** [comment] 2019-12-17 10:28
@UnderstrapFramework feel free to close out my issues as you make adjustments. Didn't mean to open so many but figured best to tackle each one at a time :)

**Comment by IanDelMar** [comment] 2019-12-17 10:31
@UnderstrapFramework maybe it would be the best to remove it completely (see #1099), rethink the whole thing and to come up with a better solution.

**Comment by UnderstrapFramework** [comment] 2019-12-17 10:42
Removed and will rethink a better solution

**Comment by pattonwebz** [comment] 2019-12-17 10:46
I'm happy to help setup the alternaitive solution. I think a theme info page + an admin notice could work for most of things. The tracking is a little complicated to manage because it requires opt-in consent from users before it can happen.

Also my suggestions come from perspective of the wordpress.org theme review team and the themes we have in the directory there. Some of the items may be suitable for themes that are not in the directory (but I'm assuming that at some point you will want to update the .org theme with what is made here in the repo as holger was doing).

**Comment by UnderstrapFramework** [comment] 2019-12-17 10:49
Thanks @pattonwebz, yes I would like to update .org soon

A more helpful solution would be ideal, il put some thought into it

**Comment by UnderstrapFramework** [comment] 2019-12-17 11:42
Hey @Thomas-A-Reinert, what would be the best way of managing this road map? A forum thread or maybe something a bit more dynamic with voting etc.?

I have an idea in my head for something on UnderStrap.com that requires signing up and voting based on:

https://codecanyon.net/item/dw-question-answer-pro-wordpress-plugin/15057949

but I don't want to put the effort into building that if its overkill

**Comment by Thomas-A-Reinert** [comment] 2019-12-17 12:15
A poll needs questions/tasks being setup before and those probably need discussion and people who assign/feel responsible for those tasks. I don´t see a problem discussing this in the internal "teams" area. No need to do that in an area that´s open to everyone. It´s not that I want to hide it from the normal users, but I think some things should be discussed internally before.

About that poll thingie - I personally will not sign up for anything I don´t _need_ regularly. And I guess the same goes for most of the other devs hier.

**Comment by Thomas-A-Reinert** [comment] 2019-12-25 00:49
@UnderstrapFramework You still didn´t reply to my request. But it seems that you did major changes to the original Website. Not up to me to judge that. But removing any link to the git-Repo, well.... No Comment

You/We need a roadmap. For EVERYTHING. We - the community - NEED to know about ANY change to make to the eco-system. It MAY be that we gonna support you - It may be not.

No matter what - GET US INFORMED _BEFORE_ YOU UNDERTAKE ANY STRANGE THINGS!

**Comment by shrthnd** [comment] 2019-12-25 13:31
I was also surprised to see the Github badge removed from the homepage.

@UnderstrapFramework and @Thomas-A-Reinert why not [create a new project](https://github.com/understrap/understrap/projects) for contributors to add tasks/features/issues to an unsorted backlog of potential jobs-to-be-done?

**Comment by 0dp** [comment] 2019-12-25 17:46
Great idea!

**Comment by Thomas-A-Reinert** [comment] 2019-12-25 19:14
@shrthnd - would you care to explain? I really don´t get the point but that´s probably just me.

**Comment by shrthnd** [comment] 2019-12-25 19:57
Sure thing,  @Thomas-A-Reinert. 

Github "Projects" are essentially kanban boards. Instead of a poll, @UnderstrapFramework might create a single  project called "Roadmap v2" setup something like this:
https://github.com/helpful-dev/understrap/projects/1

Contributors are logged in and participating through github.com (specifically, the Understrap repository page) there won't be any additional account registration needed to add issues to the board. It's also possible to import existing issues which feels like it has the potential to be useful.

¯\_(ツ)_/¯

**Comment by 0dp** [comment] 2019-12-25 20:53
Yeah so ideas and suggestions for improvements can be gathered in one place. But not sure if it's a great place for discussing.

**Comment by shrthnd** [comment] 2019-12-25 22:07
> Yeah so ideas and suggestions for improvements can be gathered in one place. But not sure if it's a great place for discussing.

I see your point. At best, _issue_ threads (like this one) imported into these boards would only be as useful as Github issues already are for group discussions. 

For real-time chat [Discord](https://discordapp.com/) has an awesome interface/experience and other open source projects (like GatsbyJS) use this as an alternative to Slack.

**Comment by Thomas-A-Reinert** [comment] 2019-12-27 23:55
Thanks for the update, @shrthnd . The discord chan should be avail at https://discord.gg/qdQgkD now the original Slack Chan @ https://understrapworkspace.slack.com/archives/CBJJAUKR8

**Comment by Thomas-A-Reinert** [comment] 2019-12-29 01:25
Hey @UnderstrapFramework : 12 days passed. No answer yet. You promise stuff and can´t keep it. AGAIN. You told me to mention you - but anyways.. you don´t answer anything.

**Comment by UnderstrapFramework** [comment] 2019-12-29 09:59
Hey Thomas, the commercial elements were removed 12 days again

Im keeping an eye on the threads you mention me in

Thanks

**Comment by Thomas-A-Reinert** [comment] 2019-12-29 22:13
Darn, this seems to become pointless. Read the topic. It says "ROADMAP". None avail yet.

No one left _any_ word about the commercial elements within the past X days. But there are still a lot of questions left unanswered if you´d read the whole thing here.

And sorry: I forgot to answer your question about the UnderStrap documentation. https://lmgtfy.com/?q=understrap+documentation - not too hard to find if one would care about it.

**Comment by Thomas-A-Reinert** [comment] 2019-12-29 22:17
Btw - you f***cked up the search function on your site, see https://understrap.com/?s=YourMother . Just  wanted to let you know

**Comment by UnderstrapFramework** [comment] 2019-12-30 12:03
Hey Thomas, thanks for the response

The search functionality is not needed right now as there's no on-site search bar but il fix that in the future sometime soon

You mentioned in the first post "Sounds ridiculous: But the updated docs NEVER got published ANYWHERE" - so I assumed it wasn't public (Google can't index non-public content) - so was wondering where they were so I could publish them

**Comment by 0dp** [comment] 2019-12-30 15:38
Understrap has its own documentation, which you should have been briefed in. It's outdated as mentioned. https://understrap.github.io

We've been working on an updated documentation, but it's far from done, so that should get some TLC to come up to date.

**Comment by UnderstrapFramework** [comment] 2019-12-30 15:57
Thanks @0dp for the link, im trying to find where to edit that right now but not having much luck

**Comment by pattonwebz** [comment] 2019-12-30 17:42
@UnderstrapFramework that documentation is handled via github pages from a different repo: this one: https://github.com/understrap/understrap.github.io.

Not sure if you have access to it, I don't have any access there.

**Comment by UnderstrapFramework** [comment] 2020-01-02 10:50
Hey @pattonwebz thanks for the link, im in now!

Seems Holger hasn't changed it since March 2019, il keep an eye out for updates to this documentation from now on

**Comment by noelspringer** [comment] 2020-01-02 11:25
@UnderstrapFramework What is the roadmap / timeframe for the next point release for WordPress.org?

**Comment by UnderstrapFramework** [comment] 2020-01-02 11:47
It should probably be soon as it hasn't been updated in a while, maybe early Feb?

I personally have no requests for any features to be added to US, just fixes that are important obviously

If anyone wants to speak out about anything they want to see included in the next update that would be helpful

**Comment by 0dp** [comment] 2020-01-02 13:32
The build system needs to be updated.
(WIP)

The docs needs to be updated as mentioned.
The build system will most likely require to have it's documentation
updated for instance.

Understrap-child needs defibrillation afterwards.

Maybe early February is optimistic for 'breaking changes'

**Comment by UnderstrapFramework** [comment] 2020-01-02 14:07
thanks @0dp

**Comment by noelspringer** [comment] 2020-01-02 14:27
OK perhaps my terminology is not correct since I was referring to a minor update that would incorporate recent merges (if they are not breaking changes), in particular Woocommerce template updates.

The UnderStrap.com website states that UnderStrap is Woocommerce ready whereas in fact it is not. 

UnderStrap 0.9.4 has Woocommerce templates that are out of date since August last year with the release of Woocommerce 3.7.0. Some subsequent Woocommerce plugin updates have incorporated additional template changes. When the UnderStrap version of a Woocommerce template is not in sync with the Woocommerce plugin template version and a user runs the WP dashboard Woocommerce Status report, the out-of-date UnderStrap templates show up in red with an alert message that the template(s) are out of date.

So this is the case for everyone running Woocommerce and using the current WordPress.org version of UnderStrap. The way to fix it is to issue an updated release which incorporates the latest Woocommerce merges. Only then will UnderStrap be "Woocommerce Ready".

**Comment by 0dp** [comment] 2020-01-02 18:44
Then maybe it's time to Branch out now.
Focussing on polishing the current master for release, and then have a new branch for features?

**Comment by noelspringer** [comment] 2020-01-05 10:28
@0dp  +1 for branching. Your suggestion sounds similar to the Gitflow approach which you may be familiar with.

Essentially, the master branch is the production branch.

A "develop" branch is created from the master branch and is also a permanent branch.
Feature/topic branches are forked from the develop branch and pull requests are made back to the develop branch.

When a new point release is required, the develop branch is merged into master and becomes the new production version.

As you pointed out, this would allow the master branch to be "polished" via the develop branch and a new point release incorporating recent, necessary updates. In the meantime other features could be worked on and pull requests made to the develop branch.

Do you think this type of workflow would be beneficial?

cc - @UnderStrapFramework

**Comment by 0dp** [comment] 2020-01-05 12:17
Exactly @noelspringer

**Comment by noelspringer** [comment] 2020-01-05 12:41
@0dp I guess the main contributors would need to agree to this workflow then.

Also, would @UnderstrapFramework, as the repo admin, need to create the permanent "develop" branch if others agree to move forward with this workflow?

In what ways do you and others consider that the current state of the master branch needs to be polished in order to move forward with a new point release?

cc- @UnderstrapFramework

**Comment by 0dp** [comment] 2020-01-05 13:05
@noelspringer yeah, but I have a feeling that this one will get support from everyone.

I believe so, as it needs to be someone with the appropriate permissions to create it or merge it in from a PR.

This is in no way a complete list:
- Woocommerce template files needs to be upgraded
- package.json dependency upgraded #1109 
- bootstrap update #1104 

@IanDelMar have made a handful of other valuable PR's lately as well.

With those tested, merged and retested I suppose we have a baseline for a new release.

...what am I missing? 🤔

**Comment by noelspringer** [comment] 2020-01-06 23:34
@0dp, @UnderstrapFramework I can confirm that all the Woocommerce templates currently used by UnderStrap are up-to-date with the Woocommerce plugin's templates.

Are there other features that need to be added?

**Comment by Thomas-A-Reinert** [comment] 2020-02-24 02:26
No annotation so far from the "repo admin" aka @UnderstrapFramework  about this topic for about two month now. Just saying that the "management" of this repo sucks a fucking lot.

**Closed** 2020-11-05 10:57 UTC
