### ISSUE TITLE
Dropdown menu not working

### ISSUE THREAD

**Issue by Mark-Artyniuk** [understrap/understrap#567] opened 2018-02-26 20:35 UTC
hello, the first level of drop down menu works as expected, however the second drop down layer doesn't display.  

https://markartyniuk.com/wp/

![menu1](https://user-images.githubusercontent.com/1077186/36693883-d128b6ce-1af9-11e8-904d-caff911dde65.png)

**Comment by 0dp** [comment] 2018-02-27 13:28
Hi @Mark-Artyniuk 
This is expected behaviour, try and inspect the elements and you'll see that you'll need additional styling fror 
<img width="888" alt="screen shot 2018-02-27 at 14 26 41" src="https://user-images.githubusercontent.com/3642367/36731259-7c1be8a0-1bca-11e8-87ba-cb7a05f39fa5.png">

**Comment by Mark-Artyniuk** [comment] 2018-02-27 16:52
Thanks for the reply, I don't see why that would be expected behavior though, if it was just needing styled thats one thing but leaving it completely hidden due to an inline style no less should be considered a bug.

**Comment by Mark-Artyniuk** [comment] 2018-02-27 16:58
Further, its also missing the data-toggle attributes.

**Comment by 0dp** [comment] 2018-02-27 20:45
It's been discussed before in #487 and here https://github.com/twbs/bootstrap/issues/21026
You might want to look into modifying the nav-walker. I can tell you that it's possible :)

**Comment by Thomas-A-Reinert** [comment] 2018-03-02 01:57
Anyway, he´s totally correct saying that the code for 3rd level etc. are generated while not being used and being hidden through an inline-style. Didnt check it, so cannot confirm. If that´s the case though, it cannot be called "intended".

Either do not generate the code or DO generate the needed CSS. Only my 2cents.

**Comment by holger1411** [comment] 2018-03-03 14:52
Its just a relic from the BS2/BS3 navwalker.
BS3 and BS4 don´t have a sub-sub navigation so UnderStrap don´t use it, too.
There are a lot of pro´s and con´s and long discussions.
But having a sub sub menu can cause a lot of trouble on mobile devices and usually means there might something wrong with your information architecture. I think that was the main reason why the Bootstrap guys remove it.

A good way would be to update the nacwalker to the latest version:https://github.com/wp-bootstrap/wp-bootstrap-navwalker
Will NOT add a sub sub menu but will clean up the code.

**Comment by pattonwebz** [comment] 2018-04-16 17:27
Hey all,

So the output of additional hidden menus is NOT the ideal behavior but was a relic from the original BS2 walker. It was also reluctantly added back in at one point as a compromose to allow people to easily create their own styles and JS handler for sub-submenus if they chose to do so (Even though Bootstrap Core does not offer those extra levels - the intention was that the walker should try to not be in the way if people wanted to roll their own multi-level support).

Setting a `depth => 2` arg on the call to `wp_nav_menu` should halt output of any hidden additional submenus in most of the walker version we released - if it doesn't feel free to open an issue at the repo linked in https://github.com/understrap/understrap/issues/567#issuecomment-370153018 and I will rewrite things to make sure it can be capped at the desired level. Master branch contains a walker for BS4, the BS3 version exists in the `v3-branch`.

**Comment by Thomas-A-Reinert** [comment] 2018-05-20 00:41
Can confirm that this _should_ be resolved if I got all of it correct.

One-level Menus work.
Two-level Menus work with depth =>2 set.
Sub-Submenus (third level menus) don´t work. Needs additional CSS. We´ll adress that in our upcoming  documentation.

Closing this issue for now as the original issue has been resolved with one of the latest releases.

**Closed by Thomas-A-Reinert** 2018-05-20 00:41 UTC
Labels: Enhancement

**Comment by pax** [comment] 2018-07-22 12:44
I had to 

1. increase the depth when calling `wp_nav_menu()` in `header.php` to render deeper than 2 (the default value) sub-menus in the source 
Ex: `'depth'           => 4,` – search for _`<!-- The WordPress Menu goes here -->`_
2. add this css lines (if not compiling sass, in `css/theme.min.css`)

```
.menu-item-has-children .menu-item-has-children:hover > .dropdown-menu {
  display: inline-block;
  left: 9em;
  top: -1ex;
}
.menu-item-has-children .menu-item-has-children:hover {
    background-color: WhiteSmoke;
}

```
![screen shot 2018-07-22 at 15 40 15](https://user-images.githubusercontent.com/116795/43045670-95d587ac-8dc5-11e8-805e-1f1a69d71676.png)

**Comment by gfrow** [comment] 2018-09-18 21:09
@pattonwebz That solved it for me by adding the 'depth' => '2',. Thank you very much for that!

**Comment by concubine1** [comment] 2025-02-01 04:39
I pinpointed the solution https://stylesheets.space/questions/the-dropdown-css-menu-appears-to-be-malfunctioning

**Comment by JoshJourney** [comment] 2025-03-18 16:54
Thank you @pax ! This issue still exists with the latest Understrap. I knew about modifying depth but didn't realize it was hidden.
