### ISSUE TITLE
TinyMCE black background

### ISSUE THREAD

**Issue by gongon2dotcom** [understrap/understrap#564] opened 2018-02-22 11:09 UTC
Hi! 
I've installed Understrap + CORE child theme 1.0.7.
Now the WP TinyMCE editor has black background.. 

I've found in custom-editor-style.css (line 9366)
 - background-color: #202123;

Why?

Thanks.
![schermata 2018-02-22 alle 12 06 27](https://user-images.githubusercontent.com/35113780/36535230-426ed522-17c9-11e8-83e4-a788a0cd6d00.jpg)

**Comment by gongon2dotcom** [comment] 2018-02-22 11:24
It's a CORE child theme problem. Same problem with 1.0.6.
1.0.4 seems to works fine.

**Comment by gongon2dotcom** [comment] 2018-02-23 16:14
CORE child theme It's full of bugs.. I uninstalled it and switched to a home-made theme.
I threw it in the trash $14...

**Comment by Thomas-A-Reinert** [comment] 2018-03-02 02:01
Hi @gongon2dotcom - sorry to hear that. I flagged your request/report, so I hope @holger1411 will take care about it. If you can - please fix the above mentioned bugs and submit a pull request.'
I know it´s not your job, but it would be really nice and contribute to the community and maybe help others! Thanks in advance.

(I am in no way involved into CORE´s child theme development, so please don´t be cross with me, okay?)

**Comment by gongon2dotcom** [comment] 2018-03-02 10:10
@Thomas-A-Reinert no problem Thomas, 14$ don't change my life..
But unfortunately I don't have time to debug CORE child theme.
Bye.

**Comment by MarieComet** [comment] 2018-03-05 06:55
Hi @gongon2dotcom,

Just checked that and can't reproduce this bug with last versions of Understrap and UnderStrap child theme.
Can you provide more details about `custom-editor-style.css` selector which apply that background color ? on line line 9366 ? Because with a fresh install, my `custom-editor-style.css` finish at line 9234.

Also, you're talking about 1.0.7, 1.0.6, 1.0.4 versions, but actually UnderStrap version is 0.8.0 and UnderStrap version is 0.5.0.
Are we talking about the same themes ?

Thanks you.

**Comment by gongon2dotcom** [comment] 2018-03-05 07:46
Hi @MarieComet. I was talking about Core Child Theme. https://understrap.com/core-child-theme/
Understrap is ok.
Thanks you!

**Comment by MarieComet** [comment] 2018-03-05 07:52
Hi,
Oh okay, I was talking about https://github.com/understrap/understrap-child, sorry for that misunderstanding.

**Comment by Thomas-A-Reinert** [comment] 2018-05-20 00:47
Closing it due to the fact that it´s related to the (commercial) CORE child-theme (sold by @holger1411 ).

Note to you who posted any problems: This issue-tracker is about the PARENT theme only. And PLEASE DO NOT post to the child-theme either - they´re both about the open-source, non-commercial versions.

You should have received a notice about support anywhere. Be it in your bill, the included readme or whatever. However - we cannot take responsibility for that. If there are no other options mentioned, please get in contact with @holger1411

**Closed by Thomas-A-Reinert** 2018-05-20 00:47 UTC
Labels: CORE Child theme
