### ISSUE TITLE
Pagination throws error

### ISSUE THREAD

**Issue by ZacharyElkins** [understrap/understrap#663] opened 2018-04-29 19:09 UTC
Please delete anything that does not apply for you!

## Issue is about..
  - [ ] a Bug Report

## Please tell us about your environment:

  - **WordPress Version:** 4.9.x
  - **OS Version:** [ Windows 10] 
  - **Browser:** [ all ]
  - **Language:** [ PHP ]

---

# Issue Overview for Bugreports
Pagination gives arror of "Invalid argument supplied for foreach() in LINE 40"

## Steps to reproduce?
Use pagination. I am using WooCommerce, if that has any effect.

## *Who* is the bug affecting?
All users.

## *What* is affected by this bug?
Pagination doesn't show, instead throws an error.

## *When* does this occur?
Ever time pagination attempts to load on page.

## *Where* on the platform does it happen?
Anywhere pagination occurs. Search, listing products, listing blog, etc.

## *How* do we replicate the issue?
Use pagination, check. If not seeing an issue, use WooCommerce.

## Are there any related Issues and/or PRs?
Pagination was changed here @0dp :
https://github.com/understrap/understrap/commit/33183a34811f4f02fd235490524b71d844bb278a#diff-80ab22429bece23e40711f16bb5f3a64

## Screenshots / Video
![pagination](https://user-images.githubusercontent.com/25933268/39410026-26abb10c-4bae-11e8-8979-ceb16adca4f8.JPG)

## Expected behavior
Pagimaton should generate.

# Todos
Fix PHP

 * Test
 * Documentation

### Other Comments
I beleive this is because of the use of wp_parse_args. When this is removed, or a seperate array of args is provided without it, it works as expected. Attempts to fix the error specifically by rewriting the foreach statement end in rendering without error but improper display/output.

**Comment by 0dp** [comment] 2018-04-29 20:11
So I don't know if WooCommerce has any effect on the pagination, but you said that WooCommerce uses its own breadcrumbs. Maybe it's the same for pagination?

What happens if you disable WooCommerce?

I have the pagination working just fine in my end on my UnderStrap development site with WooCommerce activated.
<img width="757" alt="screen shot 2018-04-29 at 21 55 05" src="https://user-images.githubusercontent.com/3642367/39410429-643a967e-4bf8-11e8-9ffe-0bb7b8cf2d7a.png">

On line 40 the foreach loop, loops through $links from line 23.
Could you try and see what the contents of $links is on one of those archives?

On line 11 we have a check `$GLOBALS['wp_query']->max_num_pages <= 1) return;`
if the max_num_pages is less or equal to 1 the function will return an error because paginate_links will return an empty result. therefor we stop execution before that happen.

But why paginate_links is empty in your case(I assume) is beyond me. 

Do you have anything interesting in your error log, when this error occurs?

**Comment by 0dp** [comment] 2018-05-05 07:59
> I beleive this is because of the use of wp_parse_args. When this is removed, or a seperate array of args is provided without it, it works as expected.

Could you provide output from php error.log to back that up?

If you read this thttps://codex.wordpress.org/Function_Reference/wp_parse_args
and look at understrap_pagination parameters, we've actually made `understrap_pagination` it pluggable by using wp_parse_args.

so calling 
```
<?php understrap_pagination( array( 'prev_text' => '>>>>', 'next_text' => '<<<<' ) ); ?>
```
Would create the pagination with custom previous and next arrows.

> Attempts to fix the error specifically by rewriting the foreach statement end in rendering without error but improper display/output.

Could you provide some code of what you've tried?

**Comment by ZacharyElkins** [comment] 2018-05-05 22:48
I’m going to run some tests on a fresh understrap install to check it. 

I’ve been pretty busy lately so it may take some time.

**Comment by 0dp** [comment] 2018-05-06 08:29
Cool, because I can't reproduce the issue you're describing

**Comment by 0dp** [comment] 2018-05-16 07:36
@ZacharyElkins there is a new version of the pagination

**Comment by Thomas-A-Reinert** [comment] 2018-05-16 22:54
Works perfectly for me now..

**Comment by 0dp** [comment] 2018-05-19 09:29
@ZacharyElkins whats up?

**Comment by 0dp** [comment] 2018-05-25 08:06
OI @ZacharyElkins i know you're here 😃 
If you don't get back to me, I can't haz fix.
Otherwise we'll just close this @Thomas-A-Reinert @holger1411 @axlright 
and you can reopen if you find anything interesting 👍

**Comment by ZacharyElkins** [comment] 2018-05-25 20:39
@0dp I apologize, I've been quite busy lately. This bug was found on a live site, not on a fresh Understrap install. I'm planning to test it out on a clean install, but if no one else is reporting this as an issue you can freely close this issue until I get the time to investigate further.

**Comment by Thomas-A-Reinert** [comment] 2018-05-26 23:42
Well, closing this for housekeeping then. As always - feel free to reopen if the problem remains!

**Closed by Thomas-A-Reinert** 2018-05-26 23:42 UTC
